version: "3.8"
services:
   db:
    image: postgres:latest
    container_name: db_dumbmerch
    ports:
      - 5432:5432
    volumes:
      - ~/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=wilson
      - POSTGRES_PASSWORD=wilson
      - POSTGRES_DB=db_dumbmerch
   frontend:
<<<<<<< HEAD
    image: wilsonakbar/fe-dumbmerch-staging:latest
=======
    image: wilsonakbar/fe-dumbmerch-production:latest
>>>>>>> f260a195699f300e27f4414bdf1e58ef150eba93
    container_name: fe-dumbmerch
    stdin_open: true
    restart: unless-stopped
    ports:
      - 3000:3000
   backend:
    depends_on:
      - db
<<<<<<< HEAD
    image: wilsonakbar/be-dumbmerch-staging:latest
=======
    image: wilsonakbar/be-dumbmerch-production:latest
>>>>>>> f260a195699f300e27f4414bdf1e58ef150eba93
    container_name: be-dumbmerch
    stdin_open: true
    restart: unless-stopped
    ports:
      - 5000:5000
